name: My First github action
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # example with gcloud service account key, except using google-github-actions/auth step. the login is handled by this action 
  job-id:
    name : on push to github
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

    

      
   