# This is a basic workflow to help you get started with Actions

name: My First github action

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  new_push:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2  

      - id: "build treasuremap docker image"
        name: "gcr.io/cloud-builders/docker"
        timeout: 600s
        args:
          - "build"
          - "-t"
          - "eu.gcr.io/$PROJECT_ID/app-my-first-api:$SHORT_SHA"
          - "."  

  

      
