name: My First github action
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # example with gcloud service account key, except using google-github-actions/auth step. the login is handled by this action 
  job-id:
    name : on push to github
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

    
# This workflow contains a single job called "sast", you should add these lines under "jobs", after "unit-testing"
  sast:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run Synopsys Detect
        uses: synopsys-sig/detect-action@v0.3.0
        with:
          scan-mode: RAPID # Can be omitted, since this is the default value
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 7.9.0
          blackduck-url: "https://ingka.app.blackduck.com/"
          blackduck-api-token: ${{ secrets.BD_TOKEN }}
  
      
   